server:
  port: 8081

spring:
  datasource:
    #url: jdbc:mysql://172.16.170.4:3306/meeting_system?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/graduation_project?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

#mybatis:
#  type-aliases-package: com.jyc.graduation.individuation.domain
#  mapper-locations: classpath:individuation/mapper/*Mapper.xml
