server:
  port: 8081

spring:
  datasource:
    #url: jdbc:mysql://172.16.170.4:3306/meeting_system?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://47.94.103.229:3306/graduation_project?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: jiang980212CHU
    driverClassName: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  type-aliases-package: com.jyc.graduation.individuation.domain
#  mapper-locations: classpath:individuation/mapper/*Mapper.xml

